### ISSUE TITLE
Birthdays are not synchronized correctly

### ISSUE THREAD

**Issue by malnvenshorn** [jobisoft/DAV-4-TbSync#10]
I'm using this add-on with TbSync and it seems that birthdays are not synchronized correctly with a CardDAV-Server (Baikal). I made some screenshots to show how it looks. If you need more information or if there is anything I can do to help you fixing this just let me know. Tsync is absolutely great :+1: 

Yes I know it's German localization - `Geburtstag` means `birthday` :wink: 

![bildschirmfoto_2018-09-13_11-15-41](https://user-images.githubusercontent.com/13801805/45479577-29ffef80-b747-11e8-9d08-bf1a2227cf48.png)
![bildschirmfoto_2018-09-13_11-20-05](https://user-images.githubusercontent.com/13801805/45479578-29ffef80-b747-11e8-9f3a-c5e2f388dbd7.png)

**Comment by jobisoft** [comment]
I am german, so that is not problem.

Could you get the raw value of the vCard birthday field? is it just "19630908"?

**Comment by malnvenshorn** [comment]
Yes, on the backend it looks like

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.1//EN
[...]
BDAY:19630908
REV:20180908T093827Z
END:VCARD
```

**Comment by jobisoft** [comment]
https://tools.ietf.org/html/rfc2426#section-3.1.5

I want to stay as close to the dav specs as possible and do not want to add special cases for differnt servers/clients.

What client generated that entry?

**Comment by jobisoft** [comment]
That RFC contradicts the one I use:

```
Note also that YYYY-MM-DD is disallowed since we are using the 
basic format instead of the extended format.
```

I got to do some research about that ... 
What client generated that entry?

**Comment by jobisoft** [comment]
Hm, sure about vCard 3 and not vCard 4?

Follow here:
https://github.com/nextcloud/contacts/issues/122#issuecomment-279232821

What do you think?

**Comment by malnvenshorn** [comment]
I'm using davdroid on Android to synchronize my calendars and contacts. Davdroid also created that entry. That client is exactly following the VCARD spects, thats why it has some issues synchronizing picture contacts with Posteo (don't know if Posteo fixed it by now).

**Comment by jobisoft** [comment]
I disagree.

The spec you linked is vCard 4 and if davdroid is using vCard 4 specs in a vCard 3, it is doing something wrong.

Also see this:
https://de.wikipedia.org/wiki/VCard#vCard_3.0

And compare the dates in the vCard 3 and vCard 4 example.

**Comment by malnvenshorn** [comment]
My mistake. It seems that something messed this up. I guess this can be closed then, thanks for your help.

**Comment by jobisoft** [comment]
There is of course some truth in your issue: I do not support vCard 4. I will add that next.

But if davdroid is sending vCards like this: https://github.com/jobisoft/DAV-4-TbSync/issues/10#issuecomment-420956007
which is a vCard 3 with vCard 4 specs, there is nothing I can do.

**Comment by rfc2822** [comment]
> The spec you linked is vCard 4 and if davdroid is using vCard 4 specs in a vCard 3, it is doing something wrong.

At the beginning of synchronization, [DAVdroid detects whether a server supports vCard 4](https://gitlab.com/bitfireAT/davdroid/blob/c0ff8f61f9e86955d5e6f0e6833477a779ee2973/app/src/main/java/at/bitfire/davdroid/syncadapter/ContactsSyncManager.kt#L134) and then [sends vCard 3 or vCard 4 with the appropriate date format accordingly](https://gitlab.com/bitfireAT/davdroid/blob/c0ff8f61f9e86955d5e6f0e6833477a779ee2973/app/src/main/java/at/bitfire/davdroid/syncadapter/ContactsSyncManager.kt#L286). (This is done by using ez-vcard which generates the vCard, and it's told to either use vCard 3 or vCard 4.) Are you sure that the server doesn't mix up vCard3/4 in this case? We have seen that in some cases.

**Comment by jobisoft** [comment]
@rfc2822 That question was not for me, right? The only thing I could do is fixing that on my client side, so when I get a vCard3 with BDAY in vCard4 format, should I rewrite it?

**Comment by malnvenshorn** [comment]
@rfc2822

Well all I can say is that Baikal supports vCard 3 and 4 (http://sabre.io/dav/). On my phone I'm using Davdroid 1.9.1 (last that supports my Android version :disappointed:). On my computer I used Thunderbird  with the Sogo-Connector before and now TbSync. I don't know which part caused this issue, but before I switched to TBSync I never noticed any issues and the synchronization worked fine. It just turned up after switching to TBSync which made me think it is an issue with this plugin. I'm also a little confused because some birthdays were in the correct format, but the most weren't. :confused: 

@jobisoft

Personally I don't think it would be a good solution, just stick to the RFC.

**Comment by brad2014** [comment]
The bug I'm seeing is that sync is deleting birthdays from my online addressbook.

## My setup:
- Nextcloud 14.0.3 using sabre/dav 3.2.2
- Thunderbird 60.3.0 (hot off the press)
- TBSync 0.7.18 
- Sabre/dav provider 0.8.29.

## To reproduce
- Sync download to TB a contact containing a RFC6350 birthday (e.g. one created on Nextcloud)
- On the TB addressbook contact edit form, edit any other field in that contact (say display name)
- Sync upload the updated contact from TB to Nextcloud

## Expected behavior
- The birthday would be visible in the edit form, 
- On upload, it would be unchanged on the server.

## Actual behavior
- the birthday field is deleted on the client (as soon as I save my edit)
- the birthday field is deleted on the server (as soon as I sync upload the edit)
- I am sad.

## More notes

Contacts created via the Nextcloud web app contain valid [RFC6350](https://tools.ietf.org/html/rfc6350#page-30) birthday dates:  
```
BDAY:19711015
```


After downloading such a contact to TB, the birthday appears in the Contact Pane as 19711015.

![image](https://user-images.githubusercontent.com/6502462/48464687-3202fc80-e795-11e8-9554-6bd17fcecd4e.png)

However, on the data entry form, the birthday is blank, and if I modify any field and save (e.g. the display name of the contact), the birthday field in the Contact Pane disappears.

![image](https://user-images.githubusercontent.com/6502462/48465769-c7ec5680-e798-11e8-926d-e72acdd3f093.png)

If I reenter the birthday into the same contact via the data entry form, it appears in the contact pane in words (this makes me think TB actually understands the date):

![image](https://user-images.githubusercontent.com/6502462/48464859-d7b66b80-e795-11e8-9a4d-2a8afcdff064.png)

And when that is sync'ed to the server, the server receives the vcard in obsolete RFC2426 format:

BDAY:1971-10-15

Nextcloud/sabre is correctly updating its birthday calendar given the obsolete BDAY format (with hyphens),  so the only breakdown in the process seems to be at the point DAV-4-TbSync takes the vcard BDAY in RFC6350 format and stuffs it into the TB addressbook card.

**Comment by jobisoft** [comment]
Thanks to @brad2014 who shed some more light onto this.

The hyphen-less style is indeed vCard3 compliant. The Standard vCard3 BDAY format is YYYY-MM-DD but the hyphens are optional, which is buried in another RFC. The full details are discussed in issue #31 

The next version of the DAV provider will have that fixed. Avail probably next week.

**Comment by jobisoft** [comment]
Sorry, discussion was in Pull Request https://github.com/jobisoft/DAV-4-TbSync/pull/32

**Comment by jobisoft** [comment]
There is a beta version avail for you to test:
https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi

You also need the most recent version of TbSync:
https://github.com/jobisoft/TbSync/releases/download/v0.7.19/TbSync-0.7.19.xpi
