### ISSUE TITLE
Enable offline support for CalDAV calendars

### ISSUE THREAD

**Issue by mbiebl** [jobisoft/DAV-4-TbSync#14]
When adding a CalDAV calendar directly in lightning, the offline support option is checked by default. See attached screenshot. Calendars that are added via tbsync do not have this option set.
I would suggest that tbsync enables this option to follow lightnings default behaviour.
![screenshot](https://user-images.githubusercontent.com/3609611/45677383-51363280-bb34-11e8-8f35-4ae51df9e180.png)

**Comment by jobisoft** [comment]
That is actually the next thing I want to add. You will get a checkbox in TbSync as well. 

Furthermore I just realized, if you change that setting in Lightning, TbSync will loose contact to the calendar because its internal reference changes and TbSync will show an info about "Calendar already managed by lightning". This is correct, because after loosing contact, TbSync wants to re-add the calendar, but the URL itself is already added. 

I have to think about how to handle that. The root cause is of course, that TbSync is just adding the calendars, but is not managing them...

**Comment by jobisoft** [comment]
Can you try this? Rename to xpi

[DAV-4-TbSync.zip](https://github.com/jobisoft/DAV-4-TbSync/files/2392347/DAV-4-TbSync.zip)

You will have to disable your account, because the offline option is a global option per account. Before re-enable your account, manually remove all calendars of that account from lightning, which have not been removed by the disable command, because TbSync lost contact.

**Comment by mbiebl** [comment]
Seems to do the trick. If I reenable the calendars with this version, offline support is enabled.

What's your plan regarding upgrades of the extension? Will it update existing subscriptions or has this to be done manually?

**Comment by mbiebl** [comment]
> So I can release and close this?

wfm
