### ISSUE TITLE
enabling offline support -> calendar is no longer marked as managed by tbsync

### ISSUE THREAD

**Issue by mbiebl** [jobisoft/DAV-4-TbSync#15]
(Not sure if this is the right component or if  this should be filed against https://github.com/jobisoft/TbSync instead)

This is related to #14.
After adding a calendar via tbsync, I enabled offline support for the Personal calendar, but now tbsync thinks that this calendar is no longer managed by tbsync.
See attached screenshot
![screenshot2](https://user-images.githubusercontent.com/3609611/45677779-5647b180-bb35-11e8-9076-cce3fbc78927.png)
Interestingly, this only seems to happen when manually enabling offline support. If I make a calendar read-only, the calendar is still marked as managed by tbsync.

**Comment by jobisoft** [comment]
Yeah, I just commented on that in the other bug. Since this issue exists, lets keep it.

**Comment by jobisoft** [comment]
I need some input on how to fix this. As I said, the reason for this behavior is that by changing the "offline support" option of a calendar actually deletes  and recreates the calendar. 

Thus, TbSync is no longer the owner of the calendar (it did not create the new one). Now, whenever TbSync finds a calendar it is supposed to be managing, it steps back and says "lightning is in charge".

How to fix:
1. Fix the behavior just for the "offline support changed" event and re-take ownership of the new calendar.
2. In general take ownership of calendars. This will effect users, who have set up their calendars by themself and install TbSync afterwards. If they remove their account in TbSync, their calendars will also be removed (because TbSync is in control). Furthermore the color of those calendars will be updated to the one defined on the server.

Option 1 is a lot more effort, because I have to detect that event. Do not know how at the moment.

What do you think?

**Comment by mbiebl** [comment]
I'm not really familiar with the internals of Thunderbird/Lightning unfortunately. E.g. I wasn't aware that turning on the offline support option basically re-creates the calendar. I can see that this complicates things.

How do you currently determine if a calendar is managed by tbsync: do calendars get an ID or something which you then look for? Does this ID change if the offline support option is enabled?

**Comment by jobisoft** [comment]
If TbSync creates the calendar XY, than it is in charge (is am allowed to delete it again, either because the user deselected the calendar in TbSync or the entire account is disabled/deleted)

If the calendar already exists (was created by lightning/user) TSync simply skips all actions on the calendar and prints the info "managed by lightning". If the user later manually deletes that calendar in lightning, Tbsync will create it on next sync and will be in full control.

So I have no property that stores this state, I just do not touch calendars which already exists.

For the offline support toggle I need to break that rule and retake control. I have yet no idea how to detect that event however.

Simply taking control in general of such already existing calendars would simplify this issue.

I do not know, if the current behaviour (not touching existing calendars) is actually confusing users.

**Comment by mbiebl** [comment]
How do you differentiate if a calendar was created by Tbsync or directly in Lightning?

**Comment by jobisoft** [comment]
Each URL/CalDAV calendar can only be added once. 

So after you connect a new account, I get all the URLs/Calendars in your account and if you selected a calendar, TbSync will try to add it to Lightning. If that URL already exists, Tbsync asumes that it has been added by lightning beforehand and goes into skip-mode.

If TbSync has added a calendar (because it did not yet exist), it has it as selected in the database, together with an internal ID and knows it is in charge. If the calendar gets deleted, TbSync still assumes to be in charge and will re-create it and store the new ID. However, if after deletion the calendar has been already recreated by some other means, TbSync will again go into skip-mode.

**Comment by jobisoft** [comment]
I found a way to identify this event and fixed just that. Can you try the latest version?
https://github.com/jobisoft/DAV-4-TbSync/releases/download/v0.8/DAV-4-TbSync.xpi

It only works, if TbSync 0.7.15.4 or higher is used:
https://github.com/jobisoft/TbSync/releases

I still do not know, if the general behavior, to not touch already existing calendars and the resulting "is already managed by lightning" message confuses the users and I should get rid of that, or not.

**Comment by mbiebl** [comment]
Doesn't seem to work for me.
If I add a calendar using tbsync, then remove the offline support (as the default is now on), tbsync marks the calendar as managed by lightning.

**Comment by mbiebl** [comment]
I have installed https://github.com/jobisoft/TbSync/releases/download/v0.7.15/TbSync-0.7.15.xpi
So apparently not?

**Comment by jobisoft** [comment]
you need the beta:
https://github.com/jobisoft/TbSync/releases/download/v0.7.15/TbSync-beta.xpi

**Comment by jobisoft** [comment]
hm, it works for the ics subscriptions, but not for real calendars.

**Comment by jobisoft** [comment]
ok, it works for me now. Can you try the attached version? 

You need to disable and re-enable your account because I added a new status flag to the db, which needs to be created first, before this works. Also, you need TbSync 0.7.15.4 again (if you have not installed it yet).


[DAV-4-TbSync.zip](https://github.com/jobisoft/DAV-4-TbSync/files/2405412/DAV-4-TbSync.zip)

**Comment by jobisoft** [comment]
Keeping it as it is. Closing.

**Comment by mbiebl** [comment]
I can confirm that it works for me as well now. Thanks!
