### ISSUE TITLE
switch appointment between icloud calendars

### ISSUE THREAD

**Issue by manact** [jobisoft/DAV-4-TbSync#187]
## iMac (27-inch, Late 2013)

TbSync version: 2.10
DAV-4-TbSync version: 1.7
Thunderbird version: 68.4.1 (64 bits)

[ ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Switch appointment between iCloud Calendars

## Actual behavior
The appointment doesn't switch after save & close
Must switch to a local calendar then switch from local calendar to desired iCloud one.

## Steps to reproduce
Open an iCloud calendar appointment and change to another iCloud calendar (same iCloud account).

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
No errors in the log file seen.

**Comment by jobisoft** [comment]
That is not a bug in TbSync. If you setup these calendars manually without TbSync doing it for you, you would get the same behaviour. I do not know if the CalDAV implementation of lightning is wrong, or the from iCloud.

What happens: The iCloud server rejects the PUT command of that event into the new calendar with a 412 status and so lightning aborts the entire process. I can see, that lightning is not issuing a new UID to the event so iCloud could deny a new event with the same UID in another book.

You will need to file a bug at
https://bugzilla.mozilla.org/home

**Comment by manact** [comment]
Thank you for your quick reply. 
You have done a precious job and I donate for that. Thank you again.

**Comment by dilyanpalauzov** [comment]
E.g. Cyrus Imap prohibits that the same user has two iCalendar objects based on UID equvallence in two different calendars, which is the intermediate step when doing PUT+DELETE at HTTP level.  The rationale is, that for server-side scheduling on PUT the server has to send iMIP (event) invitations to the attendees, and on DELETE to send iMIP cancellations.  This would be very complicated to get right.

The right way to switch the calendars is to use the MOVE HTTP verb (instead of PUT+DELETE).  You might want to file this towards the Calendar component/CalDAV provider in TB, if it is not reported yet.

**Comment by jobisoft** [comment]
@dilyanpalauzov : Thanks for identifying the root cause. That MOVE command sound like something TB should learn. Creating a bug in the calendaring component would be the best.

**Comment by dilyanpalauzov** [comment]
This is tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=702570.
