### ISSUE TITLE
Phonetic names are not synced

### ISSUE THREAD

**Issue by YingzhouLi** [jobisoft/DAV-4-TbSync#230]
## Your environment

TbSync version: 2.16
DAV-4-TbSync version: 1.18
Thunderbird version: 78.2.2

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Phonetic names (including phonetic first name,  phonetic middle name,  phonetic last name) are synced with Google contacts.

## Actual behavior
The phonetic names in google contacts are not imported into Thunderbird. Changing phonetic names in Thunderbird neither changes the phonetic names in google contacts.

## Steps to reproduce
1. Link a google contants.
2. Change phonetic names in Thunderbird and find no change in Google contacts.
3. Change phonetic names in Google contacts and find no changes in Thunderbird.

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists.
