### ISSUE TITLE
Too many authentication reqests

### ISSUE THREAD

**Issue by somzoli** [jobisoft/DAV-4-TbSync#244]
## Your environment

TbSync version:
DAV-4-TbSync version: 1.24
Thunderbird version: 78.5.1

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.
 -No.

## Expected behavior
Authentication to the Caldav/Cardav server is only happens once, than each request use this, not authenticate each requests.

## Actual behavior
Each request makes an authentication to the server. This makes a huge load to the authentication server.

## Steps to reproduce
TBsync + Caldav/Carddav Provider with Custom Configuration (Caldav + Carddav same server), then make a syncronization and check server logs. 
It show each caldav reqest makes an authentication. 

Can you help with this?

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
