### ISSUE TITLE
vCardData[vCardField.item] is undefined

### ISSUE THREAD

**Issue by fregod** [jobisoft/DAV-4-TbSync#258]
## Your environment

TbSync version:2.19
DAV-4-TbSync version:1.24
Thunderbird version:78.7.1

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
synchronizing without error

## Actual behavior
JAVASCRIPT ERROR
vCardData[vCardField.item] is undefined

getVCardFromThunderbirdContactCard@chrome://dav4tbsync/content/includes/tools.js:1148:86
localChanges@chrome://dav4tbsync/content/includes/sync.js:850:69

## Steps to reproduce
open tbsync windows, click on Synchronize now and wait till it reaches some address book entry that it doen't like and stop with an error message

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists.
