### ISSUE TITLE
[Windows] When selecting a phone number type in the address book, the text is white-on-white.

### ISSUE THREAD

**Issue by HeyBanditoz** [jobisoft/DAV-4-TbSync#260]
## Your environment

TbSync version: 2.21
DAV-4-TbSync version: 1.24
Thunderbird version: 78.10.0

- [x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
The text should be black-on-white.

## Actual behavior
The text is white-on-white, making it difficult to select the correct type.

## Steps to reproduce
1. Open Thunderbird, with dark theme enabled.
2. Install the following addons: TbSync, Provider for CalDAV && CardDAV
3. Open the Address Book in Thunderbird.
4. Create a new contact, or edit an existing one. (Do this in a book that is synced with TbSync.)
5. Under the "Contact" tab, edit or create a new phone number.
6. Select the phone type, or home or work.
7. The text is white-on-white.

![thunderbird_1bXepd41uv](https://user-images.githubusercontent.com/7574664/115630478-4c742500-a2c1-11eb-8d8e-d645e34aaea2.png)

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
