### ISSUE TITLE
Contact photo's are not imported from icloud

### ISSUE THREAD

**Issue by ThaiDutchKees** [jobisoft/DAV-4-TbSync#273]
## Your environment

TbSync version: 3.0.1
DAV-4-TbSync version: 2.0.2
Thunderbird version: 91.1.2

## Expected behavior
Contact photo from iCloud is supposed to show up somewhere in Thunderbird address book...

## Actual behavior
Contact photo from iCloud  is NOT shown in Thunderbird address book: NOT in the list, NOT in the contact specs and also NOT in the Caldav (editing) contact specs.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by 5crambler** [comment]
I have the same issue with all of my iCloud vCards - see screenshot below.
I'm a bit hesitant to send my logfile since I don't want all my contacts to float around on the web...
![Screenshot 2022-01-27 TbSync icloud photos](https://user-images.githubusercontent.com/83308760/151295974-6ff5223a-ced9-4709-b40f-de249202aae5.png)

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
