### ISSUE TITLE
[DAV 2.0.2] Freeze with sync

### ISSUE THREAD

**Issue by wonao** [jobisoft/DAV-4-TbSync#274]
## Your environment

TbSync version:  3.0.1
DAV-4-TbSync version: 2.0.2
Thunderbird version : 91.2.1

## Expected behavior

Thunderbird would run normally, without latency

## Actual behavior

Since I install TbSync on TB 91.2.1, there's regurlarly very big latency : it freezes with the mouse turning symbol a long time as if it synchronises.  yes

## Steps to reproduce
Installing a caldav client with aproximately eight subcalendars calendars synchronized with a self hosted caldav server.
On another PC, on the same network, the problem does not occur using same version of your plugins and TB.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
Done a little while before.

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
