### ISSUE TITLE
First eMail in contact record -not- the primary (but should be)

### ISSUE THREAD

**Issue by exapplerep** [jobisoft/DAV-4-TbSync#275]
##  Windows 10 (latest release version and updated as of this date)

TbSync version: 3.0.1
DAV-4-TbSync version: 2.0.2 (assuming you mean "Provider for CalDAV & CardDAV")
Thunderbird version: 91.5.0 (release channel)

## Expected behavior 
Multiple eMail addresses entered for a single contact (named John Smith in this example - no other "john" in the addressbook). Put in order thusly:
ccc@gmail.com
bbb@yahoo.com
aaa@mac.com

Expected that ccc@gmail would be the **first** suggested eMail in an outgoing message regardless of whether I type "ccc" or "john"

## Actual behavior
aaa@mac.com will be the first suggested (and highlighted) eMail and remain so even if I type the _complete_ ccc@gmail.com address.

## Steps to reproduce
See Expected behavior section.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email). DONE

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
