### ISSUE TITLE
sync TB list and CardDAV group

### ISSUE THREAD

**Issue by alexis26** [jobisoft/DAV-4-TbSync#277]
Hi,
Is there a way to synchronize 'lists' in Thunderbird and 'groups' in CardDAV?
Merci

## Your environment
TbSync version:3.0.2
DAV-4-TbSync version:2.0.2
Thunderbird version:91.6.1

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists.
