### ISSUE TITLE
Prioritise often used E-Mail address

### ISSUE THREAD

**Issue by stephankoenig** [jobisoft/DAV-4-TbSync#292]
TB 68.12.1 (I have some old addons so not ready to update)

First of all: Thank you soooo much for all your work on TbSync. I appreciate it very much!

Quick question: When using a "normal" address book (and syncing with a different addon) Thunderbird knew the recipients I was using all the time and brought them up first. For example, my wife's name starts with a "w" and as I email her all the time, her name came up first when typing "w".

I lost that when I started working with TbSync. 

Will that come back after a while as TB learns, or is that not an option here?

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
