### ISSUE TITLE
Completed tasks removed from NextCloud

### ISSUE THREAD

**Issue by nerozero** [jobisoft/DAV-4-TbSync#295]
## Your environment
Linux mint 20.2

TbSync version: 2.22
Thunderbird version: 78.13.0 (64-bit)
Nextcloud: 20.0.13

## Expected behavior
Leave completed tasks to be visible/available on a cloud side

## Actual behavior
Right after marking task as completed in thunderbird, the completed task is removed from cloud

## Steps to reproduce
Create task in TB,
Give some progress in task in TB,
Mark Task Completed in TB

results: 
  Completed Task available/visible in TB, but not visible/removed from Nextcloud web interface

Debug log was an empty file...

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
