### ISSUE TITLE
Option for syncing contact groups via categories and VCards simultaneously

### ISSUE THREAD

**Issue by mkraemer0** [jobisoft/DAV-4-TbSync#296]
It would be nice to have both options simultaneously for other clients who only support categories. The current option for categories only ist not as good because VCard groups are better when a client support that.

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird feature request.
