### ISSUE TITLE
Thunderbird lists sync only one-way to contact groups

### ISSUE THREAD

**Issue by mkraemer0** [jobisoft/DAV-4-TbSync#297]
I'm using Baïkal 0.8.0 as CardDAV server and in TbSync 2.21 the option "Kontaktgruppen als Thunderbird-Listen synchronisieren" is marked.

When I add lists in Thunderbird 78.10.2 they are synced correctly to the Baïkal server as contact groups.

But when I add with my Android phone via DAVx⁵ a contact group to the Baïkal server it isn't synced to Thunderbird. I've checked with the InfCloud web client that the group is correctly synced to the server.

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
