### ISSUE TITLE
Preferred email format forec to "Plain Text"

### ISSUE THREAD

**Issue by LapinFou** [jobisoft/DAV-4-TbSync#300]
## Your environment

TbSync version: 1.7
Thunderbird version: 60.6.1 (32 & 64 bits)

- [x]  Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

CardDAV server is running on a Synology NAS.
Client are: TbSync on one side and an Apple iPhone7 (iOS 12.2) on the other side.
By default, the field "Preferred email format" (not sure of the translation, since I'm using the French version)  is always "Plain Text".
I cannot change this parameter with my iPhone.
I can change it to "HTML" with TbSync, but as soon as my iPhone update its contact list, the field reverted back to "plain text".

BR,
Seb

**Comment by jobisoft** [comment]
I am cleaning up older issues. Since Thunderbird 102, TbSync/DAV is using the native built-in CardDAV and CalDAV sync. TbSync is now only doing the simplified resource discovery, but any found calendar or address book is synced by Thunderbird.

Closing this issue, because it deals with the old TbSync CardDAV sync, which no longer exists. If this issue remains, it is a Thunderbird bug.
