### ISSUE TITLE
Trouble setting up TbSync/DAV in TB102

### ISSUE THREAD

**Issue by GrizzlyAK** [jobisoft/DAV-4-TbSync#307]
## Your environment

WIN10
Using TbSync for the following:
-- iCloud Calendar (OAUTH)
-- Web Hosted CardDAV server using UN/PW

TbSync version: 4.3
DAV-4-TbSync version: 4.3
Thunderbird version: 102.3.3

This was working fine in TB 92. I am SERIOUSLY confused as to what is required, what is native, and HOW to upgrade effectively.

## Expected behavior
... Upgrade TB to 102, upgrade TbSync/DAV to 4.3, things work

## Actual behavior
... Upgraded TB to 102, upgraded TbSync/DAV to 4.3, things seem to work, i.e., my iCloud calendars sync both ways and my hosted Address Books sync both ways. 

Here's the issue:
It is working, but I am not sure if that is because the information is left over from TB 92 or not. Also, the DAV-4-TbSync Add-on says it is _no longer needed_, that TbSync using TB native sync, but I don't think that is the case for iCloud. (right?) The sync still seems to work in TB even if I disable the DAV-4-TbSync Add-on. But, with it disabled, TbSync _now_ says the following: _This account requires the DAV synchronization provider, which is currently not installed,_ and provides the link for the DAV-4-TbSync! So, which is it?

Can someone PLEASE provide some clear instructions for this particular setup (iCloud Calendar, hosted CardDAV server), along with what is required and what isn't now in terms of TbSync and DAV-4-TbSync? Please?

**Comment by jobisoft** [comment]
TbSync/DAV is now only a control front-end for CalDAV and CardDAV accounts. It does not sync, it only creates the address books and calendar entries in Thunderbird for you. Thunderbird is then syncing those with your server.

Why does TbSync/DAV still exists?

1. Thunderbird itself is not able to discover/find iCloud resources (but it can sync them, if the proper URLs have been used to set up the iCloud address books and calendars)

2. Thunderbird does not (yet) support to re-visit the list of available resources on your server and subscribe to a new resource, you have to go through the entire setup procedure (includig providing username and password) - TbSync/DAV just lets you refresh the list of available resources and change your subscriptions.

So after you have set up your remote address books and calendars, you may completely remove TbSync + DAV-4-TbSync.

**Comment by jobisoft** [comment]
A remark for updating from TB91 to TB102:

Before TB102, TbSync/DAV created its own CardDAV address books, which were NOT synced by Thunderbird, but by TbSync. These address books are dead in 102. Nobody is syncing them any more: TbSync no longer can, because I removed the sync code, and for Thunderbird, it looks like a normal local address book and it is not touching it.

If you hit the sync button in TbSync in 102, it will tell you, which of your resources are dead. Simply unsubscribe them (untick them in the TbSync manager), and then resubscribe them -> TbSync will create the new Thunderbird CardDAV address books.

Nothing changes for CalDAV. TbSync never had its own CalDAV sync code and has always just discovered the proper URLs here and setup the (lighning) calendars for you.

**Comment by GrizzlyAK** [comment]
Thanks John, that is very helpful in understanding what is what now. I s have it working on my laptop and will try it on my main workstation next. I was really confused about the roll of the DAV-4-TbSync at this point. It is still needed when using TbSync to set things up, but you are saying that neither are needed once that is done, correct? 

One last point, TbSync did sync my iCloud Tasks in the past, but I never used them on my iPhone, until now, and apparently it has changed to _Reminders_. Once I "upgraded" that on my iPHone, I got an error in TB, probably because the Task calendar resource disappeared. So I Disabled iCloud in TbSync again, and rediscovered, and it now says Reminders, but I'm getting a connection error. No big deal, but does TbSync support the iCloud Reminders?

Thanks again.

**Comment by paulwarwicker** [comment]
Another comment for those looking to upgrade, I had the Addon Compatibility Check extension installed (https://addons.thunderbird.net/en-GB/thunderbird/addon/addon-compatibility-check/?src=search) which had blocked my upgrade until you had released a fixed version. Once you had, everything upgraded automatically perfectly okay. There was a minor tweak required to Contacts, but that could be fixed in the TbSync account manager menu.

@jobisoft thank you for what is an indispensable extension for me

**Comment by GrizzlyAK** [comment]
Thanks John. That last part explains exactly what I'm seeing. I really didn't use tasks anyway, but was concerned about the error. 

I appreciate the responses and additional information. I just sent you a Benjamin for your trouble and efforts. Cheers.

**Comment by GrizzlyAK** [comment]
I just upgraded my desktop from existing TB 92 to 102.3.3 with TbSync as follows and everything works perfectly.

(1) I disabled both my iCloud Calendar and Hosted DAV Address Books in TbSync Add-on
(2) I installed TB 102 using installer from Windows (TB upgrade only showed next v92)
(3) TbSync/DAV was automatically updated (silently) to compatible 4.3
(4) I enabled both my iCloud Calendar and Hosted DAV Address Books in TbSync Add-on, which were discovered
(5) Sync is working

All is well.
