### ISSUE TITLE
Not compatible with Thunderbird 102.2.2

### ISSUE THREAD

**Issue by jotkah** [jobisoft/DAV-4-TbSync#308]
Hi Folks,

after my distributor upgraded to Thunderbird 102.2.2 (Linux Mint), i got an error message that the DAV provider cannot be started because it is not compatible with this version of Thunderbird.

Greetings from Germany,
Joerg

**Comment by jobisoft** [comment]
There are already a couple of related closed issues to this question. 102.2 is old, broken and not supported. Update to 102.4.

**Comment by jobisoft** [comment]
Please check thunderbird.net. I work for them. 102.4 is current release. I have no idea why your distro is still shipping an old and know to be broken version. It eats your categories.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/DAV-4-TbSync/wiki/Since-Thunderbird-102,-TbSync-DAV-is-using-native-CardDAV-sync

But even if you do not need TbSync anymore, I still suggest to always use the latest official release. So many things have been fixed since 102.2.

Abandoning TB instead of updating sounds a bit extreme, but I am happy if you found a solution which works for you.
