### ISSUE TITLE
Contacts not synchronised

### ISSUE THREAD

**Issue by tualatin** [jobisoft/DAV-4-TbSync#311]
## Your environment

TbSync version: 4.3
DAV-4-TbSync version: 4.3
Thunderbird version: 102.7.1

## Expected behavior
Conacts should synchronized into Thunderbird again.

## Actual behavior
No contacts from my nextcloud instance are synchronized into Thunderbird.

## Steps to reproduce
Do a TBSync synchronization against nextcloud, only the calendar items available after synchronization.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I would like to point you all to this document:
https://github.com/jobisoft/DAV-4-TbSync/wiki/Since-Thunderbird-102,-TbSync-DAV-is-using-native-CardDAV-sync

TbSync uses native CalDAV/CardDAV sync and it only exists because users requested to keep it due to its extended discovery methods.

There should be no difference between setting up the resources manually in Thunderbird. Please re-open this issue, if this is not the case after all.
