### ISSUE TITLE
New contacts are not syncronized to CardDAV Server

### ISSUE THREAD

**Issue by valbaum74** [jobisoft/DAV-4-TbSync#315]
## Your environment
Windows 8, Enterprise; 

TbSync version: 4.3
Thunderbird version: 102.7.2 (64-Bit)
CardDAV Server on DMS: 6.0.10-0153 (DSM 6.2.4-25556 Update 6)

## Expected behavior
I create a new contact in the Address book, after the sync the contact should be on the CardDAV Server

## Actual behavior
I create a new contact in the Address book, after the sync the contact IS NOT on the CardDAV Server. Changes in exising contacts are correctly synced.

## Steps to reproduce
1) Create a new contact
![NewContact](https://user-images.githubusercontent.com/125352428/218689583-d632ffd1-fea4-4994-9ba8-ac3ac4c7e49f.jpg)
2) Sync is started an says OK
![Sync_OK](https://user-images.githubusercontent.com/125352428/218689677-081ac7d8-9c1d-4e96-8203-23bcfd7edbd9.jpg)
3) New Contact is not on the server
![NewConcactNotOnServer](https://user-images.githubusercontent.com/125352428/218689755-ce9087b9-c024-4f88-abd8-38f363df3c06.jpg)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I would like to point you all to this document:
https://github.com/jobisoft/DAV-4-TbSync/wiki/Since-Thunderbird-102,-TbSync-DAV-is-using-native-CardDAV-sync

TbSync uses native CalDAV/CardDAV sync and it only exists because users requested to keep it due to its extended discovery methods.

There should be no difference between setting up the resources manually in Thunderbird.
