### ISSUE TITLE
Notice: The DAV provider is End-Of-Life and will not be worked on anymore

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/DAV-4-TbSync#317]
Thunderbird has native support for CalDAV/CardDAV and the provider is no longer needed.

**Comment by return42** [comment]
Many thanks for your commitment over the last few years :+1:

**Comment by jobisoft** [comment]
The only remaining "feature" of this add-on, which is not yet supported by Thunderbird, is the detection of iCloud resources.

I am investigating what needs to be done and will file patches to add iCloud support to Thunderbird.

- [ ]  CalDAV: https://phabricator.services.mozilla.com/D206253
- [ ] CardDAV

**Comment by provelo-ict** [comment]
Hello @jobisoft.

First of all, thank you so much for TbSync and its Caldav module.

I hear that you are sunseting the DAV provider (although there is always a doubt when something is announced on April Fool's day 😅).

Since I know you are directly involved in Thunderbird team, could I suggest that you only do so when it is possible to connect to a DAV server re-using saved credentials (https://bugzilla.mozilla.org/show_bug.cgi?id=1790581) and when it is possible to deselect all calendars and reselect the chosen ones manually ( https://bugzilla.mozilla.org/show_bug.cgi?id=1733959 ).
A nice addition would be the ability to use categories (https://bugzilla.mozilla.org/show_bug.cgi?id=1764184)

With those features, we would have features parity (as long as my usage in a smallish non-profit organization is concerned at least... 😳)

Sorry if this issue is not the proper channel to address this, but I don't know how to help advance those tickets.

**Comment by jobisoft** [comment]
The final sunset version of the DAV provider has been uploaded to ATN. This repository will be archived.

**Comment by jobisoft** [comment]
> Hello @jobisoft.
> 
> First of all, thank you so much for TbSync and its Caldav module.
> 
> I hear that you are sunseting the DAV provider (although there is always a doubt when something is announced on April Fool's day 😅).
> 
> Since I know you are directly involved in Thunderbird team, could I suggest that you only do so when it is possible to connect to a DAV server re-using saved credentials (https://bugzilla.mozilla.org/show_bug.cgi?id=1790581) and when it is possible to deselect all calendars and reselect the chosen ones manually ( https://bugzilla.mozilla.org/show_bug.cgi?id=1733959 ). A nice addition would be the ability to use categories (https://bugzilla.mozilla.org/show_bug.cgi?id=1764184)
> 
> With those features, we would have features parity (as long as my usage in a smallish non-profit organization is concerned at least... 😳)
> 
> Sorry if this issue is not the proper channel to address this, but I don't know how to help advance those tickets.

I will keep an eye on those bugs and see what I can do.

**Comment by CorrTi** [comment]
Thank you for your Work! It was a great Add-on
