### ISSUE TITLE
DavMail Proxy not work

### ISSUE THREAD

**Issue by sinya13** [jobisoft/DAV-4-TbSync#62]
## Your environment

TbSync version: 1.0.23
DAV-4-TbSync version: 0.10.36
Thunderbird version: 60.4.0

[ X] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

http://davmail.sourceforge.net/
This is a convenient free proxy between MS Exchange and CalDav/CardDav. 

## Expected behavior

It is expected that a calendar / address book will be found there.

## Actual behavior

However, the DAV-4-TbSync does not perceive it as a CalDav / CardDav server.  For example, Mozilla Sunbird (or Mozilla Lightning) there at the same time CalDav server with a calendar sees.

DAV-4-TbSync gives errors:
status.caldavservernotfound
or
status.carddavservernotfound
And does not take it as a data source.

It would be interesting for DAV-4-TbSync to learn how to work with this good proxy!

**Comment by jobisoft** [comment]
Can I have a debut report of such a failed attempt? 

You are using the beta and the beta has a “manual setup” where you can define the urls for your server. It should work with the correct URLs.

**Comment by sinya13** [comment]
Sent log

**Comment by sinya13** [comment]
Good! Thanks!
Truncation of the standard for DavMail URL:
http://192.168.58.110:1080/users/test1@company.com/calendar
up to the view
http://192.168.58.110:1080/
Makes everything workable!

But this is not a very obvious step for a simple user!
Perhaps should make the setting "DevMail proxy compatibility mode" in DAV-4-TbSynk!
To even the standard DevMail URL is automatically clipped to the final part

users/test1@company.com/calendar

And everything began to work immediately!

**Comment by jobisoft** [comment]
You really have a misconception there.

http://192.168.58.110:1080/users/test1@company.com/calendar

is NOT the standard DavMail URL, it is the URL to a single resource, a calendar named "calendar".

There is no need for a special option because every user has to get this right and I cannot do more then writing it ("use the base URL of your server") directly in the creation dialog (I will try to make it even more clear). But I also cannot simply clip everything from the host because in manual setup the user is allowed to add any url as he likes:

host.server.org/SOGo
host.server.org/beta/owncloud

etc.

Best regards,
John
