### ISSUE TITLE
PROPFIND request goes over http and doesn't follow redirect

### ISSUE THREAD

**Issue by Saviq** [jobisoft/DAV-4-TbSync#67]
## Your environment

TbSync version: 1.0.30
DAV-4-TbSync version: 0.10.41
Thunderbird version: 60.4.0

[x] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Adding a nextcloud-based account should work. The PROPFIND request should follow the 301 redirect.

## Actual behavior
Getting `UNKNOWN_NETWORK_ERROR`:
```
URL:
http://[my-cloud]/remote.php/dav (PROPFIND)
```

## Steps to reproduce
Set up a HTTP → HTTPS redirect on your DAV server, try to add the account in TbSync. "Use secure connection" is enabled, too.

**Comment by jobisoft** [comment]
Please check:
https://github.com/jobisoft/DAV-4-TbSync/issues/41

And retry. I do all the things you say in your report. If it still does not work with that setting changed, please contact me via email and Tell me your URL, Sonic an test for myself.

**Comment by jobisoft** [comment]
I will close this as WONTFIX, because the connection to your server dies on an internal network library used by Thunderbird. I cannot fix that.

As I have written you, your server looks strange. You redirect incomming https request back to http and then try to redirect back to https (which fails with TB).

**Comment by Saviq** [comment]
Hey, thanks for your pointers. It was nginx configured to redirect the well-known path to `$scheme`, but I've haproxy in front of the nginx over HTTP, so the redirect was incorrect. Fixing that made TbSync work fine.

Thanks again!

**Comment by jobisoft** [comment]
This is one of those OMFG moments. 

I am currently investigating another issue and finally found, that you where right. I do not follow redirects from http to https. I follow all other redirects, but not that one.

You *should* be able to set up your connection as http and since your server redirects to https, TbSync should follow. But it does not. Currently fixing this. Wanted to say thanks and sorry.

**Comment by Saviq** [comment]
Heh, so the issue I filed was indeed a problem, just not mine ;)
