### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by MyBrainNL** [jobisoft/DAV-4-TbSync#99]
## Your environment

TbSync version: 1.7
DAV-4-TbSync version: 0.15.0.2
Thunderbird version: 60.8.0

## Expected behavior
automatic synch

## Actual behavior
getting an error:

folders[unhandledFolders[t][i]] is undefined

dav.sync.folderList<@chrome://dav4tbsync/content/sync.js:267:17
TaskImpl_run@resource://gre/modules/Task.jsm:326:42

## Steps to reproduce
...just wait for it;
setting up my new baikal 0.5.3 installation.
added two account, one calendar per account, works fine until the error shows and things go sideways.

**Comment by MyBrainNL** [comment]
maybe a server issue   https://github.com/sabre-io/Baikal/issues/215
i just changed the server to basic authentication; let's see what happens...

**Comment by jobisoft** [comment]
The issue you referred to is not related to this report (but what a coincidence: I actually send in a patch for Thunderbird 68 to fix the bug you referred to).

 To reproduce this, I just have to setup a new account and sync a few times, without actually changing anything on the server or the client?

**Comment by MyBrainNL** [comment]
Hi John,

Thank you for the quick response; This is my first time configuring my own server, so I am not sure if it is a server config error, or something in the client. The javascript error could maybe be intercepted and avoided.

Anyway, I setup two users for you on my server. I just e-mailed you the details.
I added both accounts to my own Thunderbird and got the error within minutes (Synchronization set to 1 minute on both accounts)
Hope you can find it...
Good luck!

Marko Hoven

**Comment by jobisoft** [comment]
Ok, i found the error. 

The error is already fixed in the new version of the AddOn for the upcoming Thunderbird 68. 

It is not easy to fix for Thunderbird 60. The main reason is indeed the issue you referred to, that Thunderbird 60 does not support multiple connections to the same server with different credentials, which I fixed for Thunderbird 68.

To work around that bug in Thunderbird 60, you must remove one of the two accounts to your server from TbSync. 

As Thunderbird 68 will be released next month, it is not worth to spend any more time on this. Hope this is ok with you

**Comment by MyBrainNL** [comment]
HI! Thank you for looking into this.
Good to know it wasn't my server... I will wait for the update.
Have a nice day!
